### nginx-errors-global.conf

# Setup error pages for all HTTP status codes
error_page 400 /.nginx-errors/html/400.html;
error_page 401 /.nginx-errors/html/401.html;
error_page 402 /.nginx-errors/html/402.html;
error_page 403 /.nginx-errors/html/403.html;
error_page 404 /.nginx-errors/html/404.html;
error_page 405 /.nginx-errors/html/405.html;
error_page 406 /.nginx-errors/html/406.html;
error_page 407 /.nginx-errors/html/407.html;
error_page 408 /.nginx-errors/html/408.html;
error_page 409 /.nginx-errors/html/409.html;
error_page 410 /.nginx-errors/html/410.html;
error_page 411 /.nginx-errors/html/411.html;
error_page 412 /.nginx-errors/html/412.html;
error_page 413 /.nginx-errors/html/413.html;
error_page 414 /.nginx-errors/html/414.html;
error_page 415 /.nginx-errors/html/415.html;
error_page 416 /.nginx-errors/html/416.html;
error_page 417 /.nginx-errors/html/417.html;
error_page 418 /.nginx-errors/html/418.html;
error_page 421 /.nginx-errors/html/421.html;
error_page 422 /.nginx-errors/html/422.html;
error_page 423 /.nginx-errors/html/423.html;
error_page 424 /.nginx-errors/html/424.html;
error_page 425 /.nginx-errors/html/425.html;
error_page 426 /.nginx-errors/html/426.html;
error_page 428 /.nginx-errors/html/428.html;
error_page 429 /.nginx-errors/html/429.html;
error_page 431 /.nginx-errors/html/431.html;
error_page 451 /.nginx-errors/html/451.html;
error_page 500 /.nginx-errors/html/500.html;
error_page 501 /.nginx-errors/html/501.html;
error_page 502 /.nginx-errors/html/502.html;
error_page 503 /.nginx-errors/html/503.html;
error_page 504 /.nginx-errors/html/504.html;
error_page 505 /.nginx-errors/html/505.html;
error_page 506 /.nginx-errors/html/506.html;
error_page 507 /.nginx-errors/html/507.html;
error_page 508 /.nginx-errors/html/508.html;
error_page 510 /.nginx-errors/html/510.html;
error_page 511 /.nginx-errors/html/511.html;
