### nginx-errors.conf

# Serve error pages html files
location ^~ /.nginx-errors/html {
  # Enable SSI to include hostname in error pages
  ssi on;
  
  # Prevent direct access to error pages
  internal;

  # Set alias for html files
  alias /usr/share/nginx/nginx-errors/html;
}

# Serve error pages assets (CSS, JS, fonts)
location ^~ /.nginx-errors/assets {

  # Allow everybody to receive error pages
  allow all;
  basic_auth off;

  # Set alias for assets (CSS, JS, fonts)
  alias /usr/share/nginx/nginx-errors/assets;
}
